version: '2'
services:
  api:
    container_name: rulzurlibrary_api
    ports:
      - 80:8888
    build:
      context: .
      dockerfile: dockerfiles/api
    volumes:
      - /var/lib/rulzurlibrary/thumbs

  captcha:
    container_name: rulzurlibrary_captcha
    image: rulzurlibrary_api
    command: ["crond", "-f", "-d", "4"]
    volumes:
      - ./assets/captcha.sh:/etc/periodic/hourly/captcha
    volumes_from:
      - api
