version: '2'
services:
  api:
    container_name: rulzurlibrary_api
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: dockerfiles/api
    volumes:
      - /var/lib/rulzurlibrary/thumbs
      - ../cache:/var/lib/rulzurlibrary/cache

  captcha:
    container_name: rulzurlibrary_captcha
    build:
      context: .
      dockerfile: dockerfiles/cli
    volumes_from:
      - api
