version: '2'
services:
  api:
    container_name: rulzurlibrary_api
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: dockerfiles/api
    volumes:
      - /var/lib/rulzurlibrary/thumbs
      - /etc/letsencrypt:/etc/letsencrypt:ro

  captcha:
    container_name: rulzurlibrary_captcha
    image: rulzurlibrary_api
    command: ["crond", "-f", "-d", "4"]
    volumes:
      - ./assets/cron.sh:/etc/periodic/hourly/rulzurlibrary
    volumes_from:
      - api
